require("dotenv").config();
const fetch = (...args) => import("node-fetch").then(({ default: fetch }) => fetch(...args));

// Check if we can send a verification message
async function checkSendAbility(phone_number) {
    const res = await fetch("https://gatewayapi.telegram.org/checkSendAbility", {
        method: "POST",
        headers: {
            "Authorization": `Bearer ${process.env.TELEGRAM_BOT_TOKEN}`,
            "Content-Type": "application/json",
        },
        body: JSON.stringify({ phone_number }),
    });

    const data = await res.json();
    return data;
}

// Send a verification message (code generated by Telegram)
async function sendVerificationMessage(phone_number, request_id) {
    const res = await fetch("https://gatewayapi.telegram.org/sendVerificationMessage", {
        method: "POST",
        headers: {
            "Authorization": `Bearer ${process.env.TELEGRAM_BOT_TOKEN}`,
            "Content-Type": "application/json",
        },
        body: JSON.stringify({
            phone_number,
            request_id,
            code_length: 6 // Telegram generates a 6-digit code
        }),
    });

    const data = await res.json();
    return data;
}

// Check if the code entered by the user is correct
async function checkVerificationStatus(request_id, code) {
    const res = await fetch("https://gatewayapi.telegram.org/checkVerificationStatus", {
        method: "POST",
        headers: {
            "Authorization": `Bearer ${process.env.TELEGRAM_BOT_TOKEN}`,
            "Content-Type": "application/json",
        },
        body: JSON.stringify({
            request_id,
            code
        }),
    });

    const data = await res.json();
    return data;
}

module.exports = {
    checkSendAbility,
    sendVerificationMessage,
    checkVerificationStatus
};
